blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from news.views import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

news/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import NewsDetailView, NewsList, ImageList
from .feeds import ArchieveFeed

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^/?$', NewsList.as_view(), name='news-list'),
    url(r'^(?P<page>[0-9]+)/$', NewsList.as_view(), name='news-list'),
    url(r'^news/(?P<slug>[\w\-_]+)/$', NewsDetailView.as_view(),
        name='news-detail'),
    url(r'^archieve/$', ArchieveFeed(), name='archieve-feed'),
    url(r'^gallery/$', ImageList.as_view(), name='image-list'),

)

news/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Image(models.Model):
    title = models.CharField('Tytuł', max_length=255)
    slug = models.SlugField('Odnośnik', max_length=255, unique=True)
    description = models.TextField('Opis', blank=True, null=True)
    image = models.ImageField('Obrazek', upload_to="static/pictures/")
    date = models.DateField('Data wykonania zdjęcia')

    class Meta:
        ordering = ["date"]
        verbose_name = "Obrazek"
        verbose_name_plural = "Obrazki"

    def __unicode__(self):
        return self.image.name


class News(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField('Tytuł', max_length=255)
    slug = models.SlugField('Odnośnik', max_length=255, unique=True)
    picture = models.ImageField('Zdjęcie', upload_to='static/pictures/', blank=True)
    text = models.TextField(verbose_name='Treść')
    pictures = models.ManyToManyField(Image, verbose_name='Zdjęcia')
    posted_date = models.DateField('Data dodania')

    class Meta:
        verbose_name = "Wiadomość"
        verbose_name_plural = "Wiadomości"

    def __unicode__(self):
        return self.title


class NoteToPost(models.Model):
    post_id=models.ForeignKey(News)
    text = models.TextField(verbose_name='Tekst komentarza')
    posted_date = models.DateTimeField('Data dodania', auto_now_add=True)
    author = models.CharField('Autor', max_length=50)

    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"

news/forms.py
from django import forms

from . import models


class AddNoteForm(forms.ModelForm):

    class Meta:
        model = models.NoteToPost
        fields = ['post_id', 'text', 'author']

news/views.py
from django.core.urlresolvers import reverse
from django.http import Http404
from django.views import generic
from django.template import RequestContext
from django.shortcuts import render_to_response

from .models import News, Image
from .forms import AddNoteForm


class NewsList(generic.ListView):
    model = News
    paginate_by = 4
    context_object_name = 'news_list'
    queryset = News.objects.order_by('-posted_date', 'title')

    def get_context_data(self, **kwargs):
        context = super(NewsList, self).get_context_data(**kwargs)
        context['all_news'] = News.objects.order_by('-posted_date')[:7]

        return context


class ImageList(generic.ListView):
    model = Image
    context_object_name = 'image_list'
    queryset = Image.objects.order_by('-date')

    def get_context_data(self, **kwargs):
        context = super(ImageList, self).get_context_data(**kwargs)
        context['all_news'] = News.objects.order_by('-posted_date')[:7]

        return context


class NewsDetailView(generic.FormView):
    form_class = AddNoteForm
    template_name = 'news/news_detail.html'

    def get_success_url(self):
        slug = self.kwargs['slug']
        url = reverse('news-detail', kwargs={'slug': slug})
        return url

    def get(self, request, *args, **kwargs):
        form = self.get_form()
        return self.render_to_response(
            self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        form = AddNoteForm(request.POST or None)
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        slug = self.kwargs['slug']
        return self.render_to_response(
            self.get_context_data(form=form, slug=slug))

    def get_context_data(self, **kwargs):
        kwargs = super(NewsDetailView, self).get_context_data(**kwargs)
        kwargs.update({'news': self.get_news(), 'all_news' : self.get_all_news()})
        return kwargs

    def get_news(self):
        slug = self.kwargs['slug']
        news = News.objects.filter(slug=slug).first()
        if news:
            return news
        else:
            raise Http404()

    def get_all_news(self):
        news = News.objects.order_by('-posted_date')[:7]
        if news:
            return news
        else:
            raise Http404()

news/templates/base.html
{% load staticfiles %}
<!-- === BEGIN HEADER === -->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <head>
        <!-- Title -->
        <title>Wakacje na Gran Canarii</title>
        <!-- Meta -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <!-- Template CSS -->
        <link rel="stylesheet" href="{% static 'css/animate.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/nexus.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'lightbox/lightbox.css' %}" rel="stylesheet">
        <!-- Google Fonts-->
        <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=PT+Sans" type="text/css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="body-bg">
            <div id="pre-header" class="container" style="height: 40px">
                <!-- Spacing above header -->
            </div>
            <div id="header">
                <div class="container">
                    <div class="row">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="{% url "news-list" %}">
                                <h1>Wakacje na Gran Canarii</h1>
                            </a>
                        </div>
                        <!-- End Logo -->
                    </div>
                </div>
            </div>
            <div id="post_header" class="container" style="height: 40px">
                <!-- Spacing below header -->
            </div>
            <div id="content-top-border" class="container">
            </div>
            <!-- === END HEADER === -->
            {% block content %}
            {% endblock %}

            <!-- === BEGIN FOOTER === -->
            <div id="content-bottom-border" class="container">
            </div>
            <div id="base">
                <div class="container padding-vert-30 margin-top-60">
                    <div class="row">
                        <!-- Contact Details -->
                        <div class="col-md-12 margin-bottom-20">
                            <h3 class="margin-bottom-10">O nas</h3>
                            <p>
                                30 sierpnia anno domini 2016 wlecieliśmy w kolejną podróż naszych marzeń na Gran Canarię.
                                To już druga Wyspa Kanaryjska w naszym dorobku. Na blogu dzielimy się naszymi wrażeniami
                                z wyjazdu. Zachęcamy do czytania i komentowania.
                            </p>
                        </div>
                        <!-- End Contact Details -->
                        <div class="col-md-1"></div>
                        <!-- Disclaimer -->
                        <div class="col-md-4 margin-bottom-20">
                            <h3 class="margin-bottom-10"></h3>
                            <p>
                            </p>
                        </div>
                        <!-- End Disclaimer -->
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- Footer Menu -->
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div id="footermenu" class="col-md-8">
                            <ul class="list-unstyled list-inline">
                                <li>
                                    <a href="#" target="_blank"></a>
                                </li>
                            </ul>
                        </div>
                        <div id="copyright" class="col-md-4">
                            <p class="pull-right">(c) 2016 Wakacje na Gran Canarii</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Footer Menu -->
            <!-- JS -->
            <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
            <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
            <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
            <!-- Isotope - Portfolio Sorting -->
            <script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}" type="text/javascript"></script>
            <!-- Mobile Menu - Slicknav -->
            <script type="text/javascript" src="{% static 'js/jquery.slicknav.js' %}" type="text/javascript"></script>
            <!-- Animate on Scroll-->
            <script type="text/javascript" src="{% static 'js/jquery.visible.js' %}" charset="utf-8"></script>
            <!-- Sticky Div -->
            <script type="text/javascript" src="{% static 'js/jquery.sticky.js' %}" charset="utf-8"></script>
            <!-- Slimbox2-->
            <script type="text/javascript" src="{% static 'js/slimbox2.js' %}" charset="utf-8"></script>
            <!-- Modernizr -->
            <script src="{% static 'js/modernizr.custom.js' %}" type="text/javascript"></script>
            <script src="{% static 'lightbox/lightbox-plus-jquery.js' %}"></script>
            <!-- End JS -->
        </div>
    </body>
</html>
<!-- === END FOOTER === -->

news/templates/news/image_list.html
{% extends "base.html" %}
{% block content %}
<!-- Main -->
		<div id="main">
			<div class="container">
				<div class="row">

					<!-- Content -->
					<div id="content" class="12u skel-cell-important">
						<section>
							<header>
								<h2>Galeria zdjec</h2>
                                <ul><center>
    {% for image in image_list %}
        {% ifchanged %}
            <br><br><li><p>{{ image.date }}</p></li>
        {% endifchanged %}
            <a href="{{ STATIC_URL|cut:"static/" }}{{image|cut:"blog/" }}" data-lightbox="image" data-title="{{ image.title }} - zdjęcie z {{ image.date }}" class="image">
            <img src="{{ STATIC_URL|cut:"static/" }}{{image|cut:"blog/" }}" height=120 alt="" data-lightbox="image-1" /></a>
{% endfor %}
    </center></ul>


							</header>


						</section>
					</div>

				</div>
			</div>
		</div>

{% endblock %}

news/templates/news/news_detail.html
{% extends "base.html" %}
{% load staticfiles %}

    <!-- Main -->
		<div id="main">
			<div class="container">
				<div class="row">

					<!-- Content -->
					<div id="content" class="12u skel-cell-important">
						<section>
							<header>
								<h2>{{ news.title }}</h2>
								<span class="byline">{{ news.posted_date|date:" d.m.Y " }}</span>
							</header>
							<a href="{{ STATIC_URL|cut:"static/" }}{{news.picture|cut:"blog/" }}" data-lightbox="image-1" class="image full"><img src="{{ STATIC_URL|cut:"static/" }}{{ news.picture|cut:"blog/" }}" alt="" /></a>
							<a name="content"></a>
                            <p>{{ news.text|safe }}</p>
                            {% for image in news.pictures.all %}
            <a href="{{ STATIC_URL|cut:"static/" }}{{image|cut:"blog/" }}" data-lightbox="image-1" data-title="{{ image.title }} - zdjęcie z {{ image.date }}" class="image">
            <img src="{{ STATIC_URL|cut:"static/" }}{{image|cut:"blog/" }}" alt="" height="120"/></a>&nbsp
        {% endfor %}
                            <a name="comments"></a>
                        <br><br><b>Komentarze:</b><br><ol>
		{% for note in news.notetopost_set.all %}
			<li><p><b>{{ note.author }}</b> - {{ note.posted_date|date:" H:i " }}, {{ note.posted_date|date:"d E Y "}}
			<br> {{ note.text }} </p></li>
        {% empty %}
			Nie dodano jeszcze komentarzy
		{% endfor %}</ol><br>
	<form method="post" class="form-horizontal" role="form">
		{% csrf_token %}
		<div class="form-group">
			<div>
				Treść:<br>
                <textaera>{{ form.text }}</textaera>
				{% for error in form.text.errors %}
					{{ error }}
				{%  endfor %}
			</div>
			<div>
				Autor:<br>
                {{ form.author }}
				{% for error in form.author.errors %}
					{{ error }}
				{%  endfor %}
			</div>
			<div>
				<input id="id_post_id" value="{{ news.id }}" name="post_id" hidden="hidden"/>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<br><button type="submit" class="btn btn-default">Dodaj komentarz</button>
			</div>
		</div>
</form>
						</section>
					</div>

				</div>
			</div>
		</div>


{% block content %}
<!-- === BEGIN CONTENT === -->
            <div id="content">
                <div class="container background-white">
                    <div class="row margin-vert-30">
                        <!-- Main Column -->
                        <div class="col-md-12">
                            <div class="blog-post">
                                <div class="blog-item-header">
                                    <h2>
                                            {{ news.title }}
                                    </h2>
                                </div>
                                <div class="blog-post-details">
                                    <!-- Author Name -->
                                    <div class="blog-post-details-item blog-post-details-item-left user-icon">
                                        <i class="fa fa-user color-gray-light"></i>
                                        {{ news.author.first_name }}
                                    </div>
                                    <!-- End Author Name -->
                                    <!-- Date -->
                                    <div class="blog-post-details-item blog-post-details-item-left">
                                        <i class="fa fa-calendar color-gray-light"></i>
                                        {{ news.posted_date|date:"d E Y " }}
                                    </div>
                                    <!-- End Date -->
                                    <!-- # of Comments -->
                                    <div class="blog-post-details-item blog-post-details-item-left blog-post-details-item-last">
                                            <i class="fa fa-comments color-gray-light"></i>
                                            Komentarze: ({{ news.notetopost_set.all.count }})
                                    </div>
                                    <!-- End # of Comments -->
                                </div>
                                <div class="blog-item">
                                    <div class="clearfix"></div>
                                    <div class="blog-post-body row margin-top-15">
                                        <div class="col-md-5">
                                            <img src="{{ STATIC_URL|cut:"static/" }}{{ news.picture|cut:"blog/" }}" width="400" alt="" />
                                        </div>
                                        <div class="col-md-7">
                                            <p>
                                                {{ news.text|safe }}</p>
                                            <br>
                                        </div>
                                        <div class="col-md-12"><br><br>
                                            {% for image in news.pictures.all %}
                                                <a href="{{ STATIC_URL|cut:"static/" }}{{image|cut:"blog/" }}" data-lightbox="image-1" data-title="{{ image.title }} - zdjęcie z {{ image.date }}" class="image">
                                                <img src="{{ STATIC_URL|cut:"static/" }}{{image|cut:"blog/" }}" alt="" height="120"/></a>&nbsp
                                            {% endfor %}
                                        <br><br>
                                        </div>
                                    </div>
                                    <div class="blog-item-footer">
                                        <!-- Comments -->
                                        <div class="blog-recent-comments panel panel-default margin-bottom-30">
                                            <div class="panel-heading">
                                                <h3>Komentarze</h3>
                                            </div>
                                            <ul class="list-group">
                                            {% for note in news.notetopost_set.all %}
                                                <li class="list-group-item">
                                                    <div class="row">
                                                        <div class="col-md-8">
                                                            <h4>{{ note.author }}</h4>
                                                            <p>{{ note.text }}</p>
                                                            <span class="date">
                                                                <i class="fa fa-clock-o color-gray-light"></i>&nbsp;{{ note.posted_date|date:" H:i " }}, {{ note.posted_date|date:"d E Y "}}</span>
                                                        </div>
                                                    </div>
                                                </li>
                                                {% empty %}
                                                    <li class="list-group-item">
                                                        <div class="row">
                                                            <div class="col-md-8">
                                                                Nie dodano jeszcze komentarzy
                                                            </div>
                                                        </div>
                                                    </li>
                                            {% endfor %}
                                                <!-- Comment Form -->
                                                <li class="list-group-item">
                                                    <div class="blog-comment-form">
                                                        <div class="row margin-top-20">
                                                            <div class="col-md-12">
                                                                <div class="pull-left">
                                                                    <h3>Zostaw komentarz</h3>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row margin-top-20">
                                                            <div class="col-md-12">
                                                                <form method="post" class="form-horizontal" role="form">
                                                                    {% csrf_token %}
                                                                    <label>Autor</label>
                                                                    <div class="row margin-bottom-20">
                                                                        <div class="col-md-7 col-md-offset-0">
                                                                            {{ form.author }}
                                                                            {% for error in form.author.errors %}
                                                                                {{ error }}
                                                                            {%  endfor %}
                                                                        </div>
                                                                    </div>

                                                                    <label>Komentarz</label>
                                                                    <div class="row margin-bottom-20">
                                                                        <div class="col-md-11 col-md-offset-0">
                                                                            <textaera>{{ form.text }}</textaera>
                                                                            {% for error in form.text.errors %}
                                                                                {{ error }}
                                                                            {%  endfor %}
                                                                        </div>
                                                                        <div>
                                                                            <input id="id_post_id" value="{{ news.id }}" name="post_id" hidden="hidden"/>
                                                                        </div>
                                                                    </div>
                                                                    <p>
                                                                        <button class="btn btn-primary" type="submit">Wyślij</button>
                                                                    </p>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>
                                                <!-- End Comment Form -->
                                            </ul>
                                        </div>
                                        <!-- End Comments -->
                                    </div>
                                </div>
                            </div>
                            <!-- End Blog Post -->
                        </div>
                        <!-- End Main Column -->
                    </div>
                </div>
            </div>
            <!-- === END CONTENT === -->
{% endblock %}

news/templates/news/news_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<!-- === BEGIN CONTENT === -->
            <div id="content">
                <div class="container background-white">
                    <div class="row margin-vert-30">
                        <!-- Main Column -->
                        <div class="col-md-12">
                            {% for entry in news_list %}
                            <!-- Blog Post -->
                            <div class="blog-post padding-bottom-20">
                                <!-- Blog Item Header -->
                                <div class="blog-item-header">
                                    <!-- Title -->
                                    <h2>
                                        <a href="{% url "news-detail" entry.slug %}">
                                            {{ entry.title }}</a>
                                    </h2>
                                    <div class="clearfix"></div>
                                    <!-- End Title -->
                                </div>
                                <!-- End Blog Item Header -->
                                <!-- Blog Item Details -->
                                <div class="blog-post-details">
                                    <!-- Author Name -->
                                    <div class="blog-post-details-item blog-post-details-item-left">
                                        <i class="fa fa-user color-gray-light"></i>
                                        {{ entry.author.first_name }}
                                    </div>
                                    <!-- End Author Name -->
                                    <!-- Date -->
                                    <div class="blog-post-details-item blog-post-details-item-left">
                                        <i class="fa fa-calendar color-gray-light"></i>
                                        {{ entry.posted_date|date:"d E Y " }}
                                    </div>
                                    <!-- End Date -->
                                    <!-- # of Comments -->
                                    <div class="blog-post-details-item blog-post-details-item-left blog-post-details-item-last">

                                            <i class="fa fa-comments color-gray-light"></i>
                                        <a href="{% url "news-detail" entry.slug %}#comments">
                                            Komentarze: ({{ entry.notetopost_set.all.count }})
                                        </a>

                                    </div>
                                    <!-- End # of Comments -->
                                </div>
                                <!-- End Blog Item Details -->
                                <!-- Blog Item Body -->
                                <div class="blog">
                                    <div class="clearfix"></div>
                                    <div class="blog-post-body row margin-top-15">
                                        <div class="col-md-5">
                                            <a href="{% url "news-detail" entry.slug %}">
                                                <img src="{{ STATIC_URL|cut:"static/" }}{{ entry.picture|cut:"blog/" }}" width="400" alt="" />
                                            </a>
                                        </div>
                                        <div class="col-md-7">
                                            <p>{{ entry.text|safe|truncatewords:40 }}</p>
                                            <!-- Read More -->
                                            <a href="{% url "news-detail" entry.slug %}" class="btn btn-primary">
                                                Czytaj więcej...
                                                <i class="icon-chevron-right readmore-icon"></i>
                                            </a>
                                            <!-- End Read More -->
                                        </div>
                                    </div>
                                </div>
                                <!-- End Blog Item Body -->
                            </div>
                            <!-- End Blog Item -->
                            {% endfor %}
                            <!-- Pagination -->
                            <ul class="pagination">
                                {% if is_paginated %}
                                    {% if page_obj.has_previous %}
                                        <li>
                                            <a href="{% url "news-list" page_obj.previous_page_number %}">&laquo; NOWSZE</a>
                                        </li>
                                    {% endif %}
                                    {% if page_obj.has_next %}
                                        <li>
                                            <a href="{% url "news-list" page_obj.next_page_number %}">STARSZE &raquo;</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                            <!-- End Pagination -->
                        </div>
                        <!-- End Main Column -->

                    </div>
                </div>
            </div>
            <!-- === END CONTENT === -->
 {% endblock %}